
spring.banner.location=banner.txt
spring.jpa.open-in-view=false
#server.port=8088
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.platform=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/diyosinfotech
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.application.name=Diyosinfotech
logging.file.name=diyosinfotech.log

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=3600000
#60000 = 1 min
# Reduce Hibernate logging verbosity
logging.level.org.hibernate.orm.connections.pooling=ERROR





